### ISSUE TITLE
Can you pls mention what is WIP ?

### ISSUE THREAD

**Issue by atendra12** [Podidiving/lgsc-for-fas-pytorch#7]
Hi, Thanks for implementing the paper in Pytorch. Can you pls also mention what specific section of paper is "work in progress" as mentioned in Readme ? Many thanks. Have a good day !

**Comment by Podidiving** [comment]
Hi!
I think everything is good to go. The only thing, that is not present is benchmark results (you can get them on your own, if you have the necessary datasets)
